name: Build and upload hpi

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn hpi:hpi -f pom.xml
    - name: upload to artifacts
      uses: actions/upload-artifact@v3
      with:
        path: target/loadrunner-cloud.hpi
        retention-days: 7
